### PR TITLE
Added `containsDelegate` method and tests

### PR DESCRIPTION
**Pull request by JRG-Developer**
I need this for unit testing purposes mainly, but I suspect it could be useful in real apps too.

:]

### CODE REVIEW

**Comment by JRG-Developer** [comment]
If accepted, can you push a new pod version to trunk too, please (minor bump)?

**Comment by jonasman** [comment]
Done. 1.0.3

**Comment by JRG-Developer** [comment]
Awesome, thanks!

**Comment by jonasman** [comment]
just submitted the trunk now 1.0.4! 
Made some more changes

**Comment by JRG-Developer** [comment]
:+1:

**Pull request merged**
